"""
Automatic project understanding (Phase 5).

Scans the TGIE workspace and emits structured summaries to ub/data/:
  project_summary.json · architecture_summary.json · module_summary.json
  dependency_summary.json · security_summary.json

These are regenerated by the self-updating watcher whenever the codebase changes,
and are also injected into UB's system context so answers stay grounded in the
*current* shape of the project (counts, deps) plus curated architectural facts.
"""
from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Dict, List

from .indexer import TGIE_ROOT, iter_files, classify_component

DATA_DIR = Path(__file__).resolve().parents[1] / "data"


def _counts() -> Dict[str, Dict[str, int]]:
    by_comp: Dict[str, Dict[str, int]] = {}
    for fp in iter_files():
        rel = str(fp.relative_to(TGIE_ROOT))
        comp = classify_component(rel)
        d = by_comp.setdefault(comp, {"files": 0, "lines": 0})
        d["files"] += 1
        try:
            d["lines"] += sum(1 for _ in fp.open("r", encoding="utf-8", errors="ignore"))
        except OSError:
            pass
    return by_comp


def project_summary() -> Dict:
    counts = _counts()
    return {
        "name": "TGIE — Transaction Graph Intelligence Engine",
        "tagline": "Real-time 3D fraud-detection ecosystem with an adversarial Blue/Red core and a local AI cognitive layer (UB).",
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "what_it_is": (
            "TGIE ingests financial transactions, builds them into a live graph, scores them "
            "with a Blue Team fraud engine, hardens that engine against an adversarial Red Team, "
            "and renders everything in a matte-black 3D trading-terminal UI. UB (Universal Brain) "
            "is the local LLM cognitive layer that understands, explains and presents the whole system."
        ),
        "components": [
            {"name": "TGIE Core Backend", "path": "backend/", "stack": "FastAPI · networkx · scikit-learn"},
            {"name": "Frontend", "path": "frontend/", "stack": "React 18 · react-force-graph-3d · three.js"},
            {"name": "UB (Universal Brain)", "path": "ub/", "stack": "Local Ollama (llama3.1:8b) + RAG"},
            {"name": "Blue Team", "path": "backend/blue_team_v2 + blue_team/bling", "stack": "Deterministic graph engine + BLING forensic service"},
            {"name": "Red Team", "path": "red_team/", "stack": "GA · MAP-Elites · PPO · GraphGAN self-play"},
        ],
        "live_urls": {
            "backend": "https://transaction-graph-engine-production.up.railway.app",
            "frontend_local": "http://localhost:3000",
            "backend_local": "http://localhost:8000",
        },
        "file_counts_by_component": counts,
        "total_files": sum(c["files"] for c in counts.values()),
    }


def architecture_summary() -> Dict:
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "services": [
            {"name": "Frontend", "port": 3000, "stack": "Vite + React 18 + three.js"},
            {"name": "TGIE Core Backend", "port": 8000, "stack": "FastAPI + Uvicorn"},
            {"name": "BLING Blue Team", "port": 8001, "stack": "FastAPI + Postgres + Neo4j + Celery"},
            {"name": "UB Service", "port": 8000, "note": "mounted on the core backend under /ub/*"},
            {"name": "Ollama", "port": 11434, "stack": "local LLM runtime"},
        ],
        "data_flow": [
            "Ingress: POST /transaction/manual (batch) or simulator feed",
            "Graph build: graph_engine/graph_manager.py (networkx) maintains nodes/edges/components",
            "Scoring: Blue Team router → V1 (ML) or V2 (deterministic, 11 detectors)",
            "Broadcast: verdicts + graph deltas over WS /ws/live (~1s)",
            "Render: GraphScene.tsx multi-scale cluster force layout + risk-intel coloring",
            "Narration: UB wakes on fraud and explains",
        ],
        "ub_pipeline": "Frontend → FastAPI (/ub) → UB AI Core → Knowledge Engine → Vector DB → Ollama → llama3.1:8b",
        "key_invariants": [
            "mergedData memoized on graphSig — prevents heartbeat reheat",
            "Never call d3ReheatSimulation() before first graphData (blank-canvas crash)",
            "Decentralized cluster forces — no global center/origin gravity",
            "Blue Team V2 is additive/opt-in; V1 untouched",
            "Red Team panel + UB are localhost/local-only by default",
        ],
        "ub_modes": ["chat", "founder", "developer", "presentation", "demo", "judge"],
    }


def module_summary() -> Dict:
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "modules": {
            "backend/": "TGIE core engine: graph_engine, simulator, blue_team(V1), blue_team_v2(11 detectors), anomaly_detection, api, ml, streaming, ub_service",
            "frontend/": "Vite SPA: GraphScene.tsx (3D graph), ai/ (risk intel + UB), components/, ub_dashboard/",
            "ub/": "Universal Brain: ai_core, knowledge_engine, ollama_service, data/, scripts/, cli.py",
            "blue_team/bling/": "BLING Blue Team API (Union Bank): detection, evidence(PDF), graph(Neo4j), ml bridges",
            "red_team/adversarial/": "Red⇄Blue self-play: agents, evolutionary_engine, quality_diversity, rl_agent, graph_gan, self_play, integration, reports/",
            "red_team/crucible/": "CRUCIBLE evolutionary fraud-genome engine + human gate + prophecy",
            "docs/": "Analysis, audits, architecture, readiness, UB_* docs",
            "deployment/": "railway.toml, nixpacks.toml, docker-compose, launchers, infrastructure/",
        },
    }


def _parse_requirements(path: Path) -> List[str]:
    if not path.exists():
        return []
    out = []
    for line in path.read_text(errors="ignore").splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            out.append(line)
    return out


def dependency_summary() -> Dict:
    backend = _parse_requirements(TGIE_ROOT / "backend" / "requirements.txt")
    bling = _parse_requirements(TGIE_ROOT / "blue_team" / "bling" / "requirements.txt")
    pkg = TGIE_ROOT / "frontend" / "package.json"
    frontend_deps: Dict[str, str] = {}
    if pkg.exists():
        try:
            j = json.loads(pkg.read_text())
            frontend_deps = {**j.get("dependencies", {}), **j.get("devDependencies", {})}
        except Exception:
            pass
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "backend_python": backend,
        "bling_python": bling,
        "frontend_npm": frontend_deps,
        "ub_runtime": {
            "llm": "Ollama (local) — llama3.1:8b primary, llama3.2:3b fast fallback",
            "embeddings": "nomic-embed-text (local)",
            "python": "stdlib + numpy (no heavy ML deps; no fine-tuning)",
        },
        "notes": [
            "scipy==1.13.0 has no wheel for Python 3.14 → local backend needs Python 3.11 or relaxed pins",
            "xgboost requires libomp.dylib; gracefully falls back to rule-based if absent",
        ],
    }


def security_summary() -> Dict:
    return {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "posture": "Advanced prototype — strong research core; production hardening required.",
        "readiness_score": "55/100 (see docs/production_readiness_report.md)",
        "critical": [
            "No authN on the public WS (/ws/live) and POST /transaction/manual",
            "Static BLUE_TEAM_API_KEY in env docs — rotate + secret manager",
            "Blue Team V2 trusts attacker-set node attributes (B8)",
            "V1 label leakage (B5): IsolationForest reads ground-truth fraud_pattern",
            "56.7% benign false-positive rate on realistic legit traffic (fixed to ~0% by provenance signal)",
        ],
        "ub_security": [
            "UB runs entirely locally via Ollama — no transaction data leaves the Mac",
            "UB service is intended for localhost / trusted-network use",
            "Knowledge index is built from the local workspace only",
        ],
    }


GENERATORS = {
    "project_summary.json": project_summary,
    "architecture_summary.json": architecture_summary,
    "module_summary.json": module_summary,
    "dependency_summary.json": dependency_summary,
    "security_summary.json": security_summary,
}


def generate_all(data_dir: Path = DATA_DIR) -> List[str]:
    data_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, fn in GENERATORS.items():
        (data_dir / name).write_text(json.dumps(fn(), indent=2))
        written.append(name)
    return written


if __name__ == "__main__":
    files = generate_all()
    print("wrote:", ", ".join(files), "→", DATA_DIR)
